# プログラム5-1(listメソッドの使用例)
# list1 = [6,2,4,3,6,1]
# print(list1.count(6))
# print(list1.count(5))
# print(list1.index(1))
# print(list1.index(6))
# list1.append(5)
# print(list1)
# list1.remove(6)
# print(list1)
# list1.pop()
# print(list1)
# list1.sort()
# print(list1)
# list1.sort(reverse=True)
# print(list1)